version: '3.7'

services:
      
  mycompanyname.abpzerotemplate.web.mvc:
    image: ${DOCKER_REGISTRY-}mycompanynameabpzerotemplatewebmvc
    container_name: mycompanynameabpzerotemplatewebmvc_container
    build:
      context: ../../
      dockerfile: src/MyCompanyName.AbpZeroTemplate.Web.Mvc/Dockerfile
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - Abp__RedisCache__ConnectionString=localhost:6379
    ports:
      - "44302:443"
    networks:
      - mycompanyname.abpzerotemplate

networks:
  mycompanyname.abpzerotemplate:
    external:
      name: mycompanyname.abpzerotemplate